### ISSUE TITLE
AppStore launcher won't launch applications

### ISSUE THREAD

**Issue by ArturCamposMaia** [BEAST2-Dev/bModelTest#3]
Hello everyone. I am fairly new to BEAST and I might be running into a problem related to general inexperience with JAVA. I have installed BEAST 2.4.5 and through the Manage Packages menu installed the latest updates for all available packages. My intention was to run the BModelAnalyser, but although the AppStore application itself opens when requested, ordering any of the available package applications to lauch does not result into new menus popping up. I am running the software on a mid 2015 Macbook Pro with OS Sierra v.10.12.3.

**Comment by rbouckaert** [comment]
This may be due to JAVA 8 not being the default JAVA version. You can test this by opening a terminal and type

    java -version

which should report something like

    java version "1.8.0_73"

To fix this, you should install the Java JDK from Oracle, not just the JAVA JRE. You can download it from http://www.oracle.com/technetwork/java/javase/downloads/index.html.

Hope this helps. By the way, it is more efficient to ask this kind of question on the beast-users mailing list.

**Comment by ArturCamposMaia** [comment]
Thanks a bunch! It helped immediately.
